services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:17.0
    restart: always
    volumes:
      - keycloak:/var/lib/postgresql/data
      - ./exports:/exports
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: ${POSTGRES_USER:-keycloak_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}

  keycloak-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak-app
    restart: always
    command:
      - start
    ports:
      - 8081:8080
    depends_on:
      - keycloak-db
    working_dir: /opt/keycloak
    environment:
      # Keycloak 管理コンソール
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-P@ssw0rd}
      # データベース種類
      KC_DB: postgres
      # データベース名
      KC_DB_URL_DATABASE: keycloakdb
      # 接続情報
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak_user}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      # 一括指定する場合は下記をアンコメントする
      #KC_DB_URL: 'jdbc:postgresql://postgres:5432/keycloak'
      KC_LOG_LEVEL: ERROR,org.infinispan:DEBUG,org.jgroups:DEBUG
      TZ: Asia/Tokyo # タイムゾーン
      # KC_HTTP_RELATIVE_PATH: '/auth' # 管理コンソールのパス。デフォルトでは「/」のため、v16 利用時と合わせたい場合に指定する
      KC_HEALTH_ENABLED: true # ヘルスチェック URL の有効化
      KC_HTTP_ENABLED: true # HTTP の待ち受け
      KC_HOSTNAME_STRICT: false
      # see https://www.keycloak.org/server/hostname#_accessing_keycloak_in_production_mode_using_http
      KC_HOSTNAME_STRICT_HTTPS: false
      # see https://www.keycloak.org/server/hostname#_backend_endpoints
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      # see https://www.keycloak.org/server/reverseproxy
      KC_PROXY: edge
      # see https://www.keycloak.org/server/features#_supported_features
      KC_FEATURES: token-exchange
      PROXY_ADDRESS_FORWARDING: true

volumes:
  keycloak:
    driver: local
